### ISSUE TITLE
Nov 2023 Meetup Checklist

### ISSUE THREAD

**Issue by andrewiggins** [seattlejs/seattlejs.com#119]
# Meetup Checklist
  
## (Immediately following previous event)
- [x] confirm location
- [x] ~~update meetup.com auto-created event with location info (if not Collective)~~
- [x] create new event in ti.to
- [x] send email via Tito to previous month's attendees with link to survey + link to tickets
- [x] update website with event json
  
## (3 weeks out)
- [x] confirm sponsor & update website
- [ ] submit invoice to sponsor
- [x] confirm speakers & update website
- [x] create calendar event and invite speakers, sponsor, & volunteers
- [x] create discord event
- [x] click "announce" on meetup.com
- [x] post tweet & paste in discord #annoucements channel

## (2 weeks out)
- [x] send email to mailing list (customer.io)

## (1 week out)
- [x] send email to meetup.com
- [x] post tweet & paste in discrod #annoucements channel

## (1-2 days before)
- [ ] send info to speakers on where/when/what
- [ ] send message to volunteers
- [ ] prepare MC slide deck, get sign-off
  
## (day of)
- [ ] If new location, tweet image of building facade so people know where to go
- [ ] bring nametags, stickers (pronouns, job status), sharpies & drink tickets
- [ ] send ti.to check-in link to volunteers in discord
- [ ] set up stage (speakers, tv, podium)
- [ ] set up chairs
- [ ] check A/V with speakers (slide/video/audio output, mic volume check, wifi connection)
- [ ] put away chairs and sound/video equipment
- [ ] clean up venue

## (day after)
- [x] ask speakers to post links to slides to `#seattlejs-meetups` channel
- [x] create meetup survey and post in Discord
- [x] create next meetup checklist
