### ISSUE TITLE
March 2024 Meetup Checklist

### ISSUE THREAD

**Issue by andrewiggins** [seattlejs/seattlejs.com#125]
# Meetup Checklist
  
## (Immediately following previous event)
- [x] confirm location
- [x] create new event in ti.to
- [x] update meetup.com auto-created event with location info (if not Collective))
- [x] send email via Tito to previous month's attendees with link to tickets + link to survey (if we create one)
- [x] update website with event json
  
## (3 weeks out)
- [x] confirm sponsor & update website
- [x] confirm speakers & update website
- [x] create calendar event and invite speakers, sponsor, & volunteers
- [x] click "announce" on meetup.com
- [x] post tweet & paste in discord #annoucements channel

## (2 weeks out)
- [x] send email to mailing list (customer.io)

## (1 week out)
- [x] send email to meetup.com
- [x] post tweet & paste in discrod #annoucements channel

## (1-2 days before)
- [x] send info to speakers on where/when/what
- [x] send message to volunteers
- [ ] prepare MC slide deck
  
## (day of)
- [x] If new location, tweet image of building facade so people know where to go
- [x] bring nametags, stickers (pronouns, job status), sharpies & drink tickets
- [x] send ti.to check-in link to volunteers in discord
- [x] set up stage (speakers, tv, podium)
- [x] set up chairs
- [x] check A/V with speakers (slide/video/audio output, mic volume check, wifi connection)
- [x] put away chairs and sound/video equipment
- [x] clean up venue

## (day after)
- [ ] ask speakers to post links to slides to `#seattlejs-meetups` channel
- [ ] create meetup survey and post in Discord
- [x] create next meetup checklist
