### ISSUE TITLE
October 2024 Meetup Checklist

### ISSUE THREAD

**Issue by andrewiggins** [seattlejs/seattlejs.com#135]
# Meetup Checklist

## (Immediately following previous event)

- [x] confirm location
- [x] create new event on lu.ma
- [x] update meetup.com auto-created event with location info (if not Collective)
- [x] update website with event json

## (3 weeks out)

- [x] confirm sponsor & update website
- [x] submit invoice to sponsor
- [x] confirm speakers & update website
- [x] create calendar event and invite speakers, sponsor, & volunteers
- [x] click "announce" on meetup.com
- [ ] post tweet & paste in discord #announcements channel

## (2 weeks out)

- [x] send email to mailing list (customer.io)

## (1 week out)

- [ ] send email to meetup.com
- [ ] post tweet
- [ ] announce in Discord #announcements channel

## (1-2 days before)

- [ ] send info to speakers on where/when/what
- [ ] send message to volunteers
- [ ] prepare MC slide deck

## (day of)

- [ ] If new location, post in #seattlejs-meetups channel image of building facade
- [ ] bring nametags, stickers (pronouns, job status), sharpies & drink tickets
- [x] #138
- [ ] set up stage (speakers, tv, podium)
- [ ] set up chairs
- [ ] check A/V with speakers (slide/video/audio output, mic volume check, wifi connection)
- [ ] put away chairs and sound/video equipment
- [ ] clean up venue

## (day after)

- [ ] ask speakers to post links to slides to `#seattlejs-meetups` channel
- [ ] create next meetup checklist
