### ISSUE TITLE
May 2023 Meetup Checklist

### ISSUE THREAD

**Issue by crtr0** [seattlejs/seattlejs.com#90]
# Meetup Checklist
# Details
**(T-3 weeks)**
- [x] lock in sponsor
- [x] lock in location
- [x] lock in speakers

# Update Materials 
**(T-3 weeks)**
- [x] update website with speakers, sponsors, etc.
- [x] update meetup.com auto-created event with details
- [x] create new event in ti.to
- [x] create discord event
- [x] prepare mc slide deck

# Promote
- [x] click "announce" on meetup.com (T-2 weeks)
- [x] send email using customer.io (T-1 week)
- [x] post tweet (T-5 days)
- [x] post in discord (T-3 days)

# Before the meetup
**(T-5 days)**
- [ ] confirm with speakers
- [x] confirm with location
- [ ] confirm with volunteers
- [ ] confirm slide deck

# Day of the meetup
**(T-0 days)**
- [x] bring nametags, stickers (pronouns, job status), sharpies
- [x] bring tickets
- [ ] send ti.to link to volunteers in discord
- [ ] set up stage (speakers, tv, podium)
- [ ] set up chairs
- [ ] check sound/video/slides with speakers
- [ ] put away chairs and sound/video equipment
- [ ] clean up venue

# After the meetup
**(T+1 day)**
- [ ] create next meetup checklist
- [ ] submit invoice to sponsor
