### ISSUE TITLE
June 2023 Meetup Checklist

### ISSUE THREAD

**Issue by crtr0** [seattlejs/seattlejs.com#95]
# Meetup Checklist
  
## (Immediately following previous event)
- [x] confirm location
- [x] update meetup.com auto-created event with location info (if not Collective)
- [x] create new event in ti.to
- [x] duplicate meetup survey and update speaker info (Google Docs)
- [x] send email via Tito to previous month's attendees with link to survey + link to tickets
- [x] create "event" and update website
  
## (3 weeks out)
- [x] confirm sponsor & update website
- [x] submit invoice to sponsor
- [x] confirm speakers & update website
- [x] create discord event
- [x] click "announce" on meetup.com
- [ ] post tweet

## (2 weeks out)
- [x] send email to mailing list (customer.io)
- [x] announce in discord

## (1 week out)
- [x] send email to meetup.com
- [x] post tweet

## (1-2 days before)
- [x] send info to speakers on where/when/what
- [x] send message to volunteers
- [x] prepare MC slide deck, get sign-off
  
## (day of)
- [x] bring nametags, stickers (pronouns, job status), sharpies & drink tickets
- [x] send ti.to check-in link to volunteers in discord
- [x] set up stage (speakers, tv, podium)
- [x] set up chairs
- [x] check A/V with speakers (slide/video/audio output, mic volume check, wifi connection)
- [x] put away chairs and sound/video equipment
- [x] clean up venue

## (day after)
- [ ] ask speakers to post links to slides to `#meetup-chat` channel
- [x] create next meetup checklist
